VAGRANTFILE_API_VERSION="2"

  Vagrant.configure(VAGRANTFILE_API_VERSION)do|config|
   # General Vagrant VM configuration.
   config.vm.box = "geerlingguy/centos7"
   config.ssh.insert_key = false
   config.vm.synced_folder ".", "/vagrant", disabled: true
   config.vm.provider :virtualbox do |v|
   v.memory = 256
   v.linked_clone = true
  end

  # Server 1.
  config.vm.define "server-01" do |app|
    app.vm.hostname = "server-01"
    app.vm.network :private_network, ip: "192.168.60.4"
  end

  # Server 2.
  config.vm.define "server-02" do |app|
    app.vm.hostname = "server-02"
    app.vm.network :private_network, ip: "192.168.60.5"
  end

end
